################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Source\ Code/Contorl/PIDFunMode.obj: ../Source\ Code/Contorl/PIDFunMode.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/Contorl/PIDFunMode.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/Contorl" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/Contorl/fpga.obj: ../Source\ Code/Contorl/fpga.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/Contorl/fpga.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/Contorl" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/Contorl/powerModule.obj: ../Source\ Code/Contorl/powerModule.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/Contorl/powerModule.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/Contorl" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/Contorl/recorder.obj: ../Source\ Code/Contorl/recorder.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/Contorl/recorder.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/Contorl" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/Contorl/svpwm.obj: ../Source\ Code/Contorl/svpwm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/Contorl/svpwm.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/Contorl" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


