################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Source\ Code/CAN/lib/CANopen/CANopen.obj: ../Source\ Code/CAN/lib/CANopen/CANopen.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CANopen.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_Emergency.obj: ../Source\ Code/CAN/lib/CANopen/CO_Emergency.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_Emergency.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_HBconsumer.obj: ../Source\ Code/CAN/lib/CANopen/CO_HBconsumer.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_HBconsumer.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_LSSmaster.obj: ../Source\ Code/CAN/lib/CANopen/CO_LSSmaster.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_LSSmaster.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_LSSslave.obj: ../Source\ Code/CAN/lib/CANopen/CO_LSSslave.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_LSSslave.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_NMT_Heartbeat.obj: ../Source\ Code/CAN/lib/CANopen/CO_NMT_Heartbeat.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_NMT_Heartbeat.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_Node_Guarding.obj: ../Source\ Code/CAN/lib/CANopen/CO_Node_Guarding.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_Node_Guarding.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_PDO.obj: ../Source\ Code/CAN/lib/CANopen/CO_PDO.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_PDO.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_SDO.obj: ../Source\ Code/CAN/lib/CANopen/CO_SDO.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_SDO.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_SDOmaster.obj: ../Source\ Code/CAN/lib/CANopen/CO_SDOmaster.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_SDOmaster.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_SYNC.obj: ../Source\ Code/CAN/lib/CANopen/CO_SYNC.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_SYNC.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_TIME.obj: ../Source\ Code/CAN/lib/CANopen/CO_TIME.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_TIME.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/CO_trace.obj: ../Source\ Code/CAN/lib/CANopen/CO_trace.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/CO_trace.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/CAN/lib/CANopen/crc16-ccitt.obj: ../Source\ Code/CAN/lib/CANopen/crc16-ccitt.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --fp_mode=relaxed --fp_reassoc=on --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/device" --include_path="D:/Yang/App/ti/CCS2001/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Yang/App/CSS/CSSv11.2/ccs/tools/compiler/ti-cgt-c2000_22.6.1.LTS/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/include" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/W5500" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/PWM" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/modbus" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/DIDO" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/GlobalVarivables" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/APP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN/lib/CANopen/DSP" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/CAN" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/Contorl" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/Source Code/BootLoader" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --define=_FLASH --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/CAN/lib/CANopen/crc16-ccitt.d_raw" --include_path="E:/project/FullPowerTestPlatform/DSP/BootLoader/powermoduletestplatform/F28377_FLASH/syscfg" --obj_directory="Source Code/CAN/lib/CANopen" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


