################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
F28377D/Source\ Code/source/F2837xD_CodeStartBranch.obj: ../F28377D/Source\ Code/source/F2837xD_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="F28377D/Source Code/source/F2837xD_CodeStartBranch.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="F28377D/Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F28377D/Source\ Code/source/F2837xD_DefaultISR.obj: ../F28377D/Source\ Code/source/F2837xD_DefaultISR.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="F28377D/Source Code/source/F2837xD_DefaultISR.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="F28377D/Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F28377D/Source\ Code/source/F2837xD_GlobalVariableDefs.obj: ../F28377D/Source\ Code/source/F2837xD_GlobalVariableDefs.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="F28377D/Source Code/source/F2837xD_GlobalVariableDefs.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="F28377D/Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F28377D/Source\ Code/source/F2837xD_Gpio.obj: ../F28377D/Source\ Code/source/F2837xD_Gpio.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="F28377D/Source Code/source/F2837xD_Gpio.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="F28377D/Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F28377D/Source\ Code/source/F2837xD_PieCtrl.obj: ../F28377D/Source\ Code/source/F2837xD_PieCtrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="F28377D/Source Code/source/F2837xD_PieCtrl.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="F28377D/Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F28377D/Source\ Code/source/F2837xD_PieVect.obj: ../F28377D/Source\ Code/source/F2837xD_PieVect.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="F28377D/Source Code/source/F2837xD_PieVect.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="F28377D/Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F28377D/Source\ Code/source/F2837xD_SysCtrl.obj: ../F28377D/Source\ Code/source/F2837xD_SysCtrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="F28377D/Source Code/source/F2837xD_SysCtrl.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="F28377D/Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F28377D/Source\ Code/source/F2837xD_usDelay.obj: ../F28377D/Source\ Code/source/F2837xD_usDelay.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="F28377D/Source Code/source/F2837xD_usDelay.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="F28377D/Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


