// clang-format off
/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode v1 to v2

    This file was automatically generated by CANopenEditor v4.2-0-g3735e28

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
*******************************************************************************/
#ifndef CO_OD_H_
#define CO_OD_H_

/*******************************************************************************
   CANopen DATA TYPES
*******************************************************************************/
   typedef bool_t       BOOLEAN;
   typedef uint8_t      UNSIGNED8;
   typedef uint16_t     UNSIGNED16;
   typedef uint32_t     UNSIGNED32;
   typedef uint64_t     UNSIGNED64;
   typedef int8_t       INTEGER8;
   typedef int16_t      INTEGER16;
   typedef int32_t      INTEGER32;
   typedef int64_t      INTEGER64;
   typedef float32_t    REAL32;
   typedef float64_t    REAL64;
   typedef char_t       VISIBLE_STRING;
   typedef oChar_t      OCTET_STRING;

   #ifdef DOMAIN
   #undef DOMAIN
   #endif

   typedef domain_t     DOMAIN;


/*******************************************************************************
   FILE INFO:
      FileName:     IO.xdd
      FileVersion:  -
      CreationTime: 12:00上午
      CreationDate: 01-01-0001
      CreatedBy:    JP
*******************************************************************************/


/*******************************************************************************
   DEVICE INFO:
      VendorName:     CANopenNode
      VendorNumber:   0
      ProductName:    CANopenNode
      ProductNumber:  0
*******************************************************************************/


/*******************************************************************************
   FEATURES
*******************************************************************************/
  #define CO_NO_SYNC                     1   //Associated objects: 1005-1007
  #define CO_NO_EMERGENCY                1   //Associated objects: 1014, 1015
  #define CO_NO_TIME                     0   //Associated objects: 1012, 1013
  #define CO_NO_SDO_SERVER               1   //Associated objects: 1200-127F
  #define CO_NO_SDO_CLIENT               0   //Associated objects: 1280-12FF
  #define CO_NO_GFC                      0   //Associated objects: 1300
  #define CO_NO_SRDO                     0   //Associated objects: 1301-1341, 1381-13C0
  #define CO_NO_LSS_SERVER               0   //LSS Slave
  #define CO_NO_LSS_CLIENT               0   //LSS Master
  #define CO_NODE_GUARDING_SLAVE         0   //NG Slave
  #define CO_NODE_GUARDING_MASTER        0   //NG Master
  #define CO_NO_RPDO                     1   //Associated objects: 14xx, 16xx
  #define CO_NO_TPDO                     4   //Associated objects: 18xx, 1Axx
  #define CO_NO_NMT_MASTER               0
  #define CO_NO_TRACE                    0


/*******************************************************************************
   OBJECT DICTIONARY
*******************************************************************************/
   #define CO_OD_NoOfElements             54


/*******************************************************************************
   TYPE DEFINITIONS FOR RECORDS
*******************************************************************************/
/*1018      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               UNSIGNED32     vendorID;
               UNSIGNED32     productCode;
               UNSIGNED32     revisionNumber;
               UNSIGNED32     serialNumber;
               }              OD_identity_t;
/*1200      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               UNSIGNED32     COB_IDClientToServer;
               UNSIGNED32     COB_IDServerToClient;
               }              OD_SDOServerParameter_t;
/*1402      */ typedef struct {
               UNSIGNED8      highestSubIndexSupported;
               UNSIGNED32     COB_IDUsedByRPDO;
               UNSIGNED8      transmissionType;
               }              OD_RPDOCommunicationParameter_t;
/*1602      */ typedef struct {
               UNSIGNED8      numberOfMappedApplicationObjectsInPDO;
               UNSIGNED32     applicationObject1;
               UNSIGNED32     applicationObject2;
               UNSIGNED32     applicationObject3;
               UNSIGNED32     applicationObject4;
               UNSIGNED32     applicationObject5;
               UNSIGNED32     applicationObject6;
               UNSIGNED32     applicationObject7;
               UNSIGNED32     applicationObject8;
               }              OD_RPDOMappingParameter_t;
/*1800      */ typedef struct {
               UNSIGNED8      highestSubIndexSupported;
               UNSIGNED32     COB_IDUsedByTPDO;
               UNSIGNED8      transmissionType;
               UNSIGNED16     inhibitTime;
               UNSIGNED8      compatibilityEntry;
               UNSIGNED16     eventTimer;
               UNSIGNED8      SYNCStartValue;
               }              OD_TPDOCommunicationParameter_t;
/*1A00      */ typedef struct {
               UNSIGNED8      numberOfMappedApplicationObjectsInPDO;
               UNSIGNED32     applicationObject1;
               UNSIGNED32     applicationObject2;
               UNSIGNED32     applicationObject3;
               UNSIGNED32     applicationObject4;
               UNSIGNED32     applicationObject5;
               UNSIGNED32     applicationObject6;
               UNSIGNED32     applicationObject7;
               UNSIGNED32     applicationObject8;
               }              OD_TPDOMappingParameter_t;
/*2120      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               INTEGER64      I64;
               UNSIGNED64     U64;
               REAL32         R32;
               REAL64         R64;
               DOMAIN         domain;
               }              OD_testVar_t;
/*2130      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               VISIBLE_STRING string[1];
               UNSIGNED64     epochTimeBaseMs;
               UNSIGNED32     epochTimeOffsetMs;
               }              OD_time_t;
/*2301      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               UNSIGNED32     size;
               UNSIGNED8      axisNo;
               VISIBLE_STRING name[6];
               VISIBLE_STRING color[3];
               UNSIGNED32     map;
               UNSIGNED8      format;
               UNSIGNED8      trigger;
               INTEGER32      threshold;
               }              OD_traceConfig_t;
/*2401      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               UNSIGNED32     size;
               INTEGER32      value;
               INTEGER32      min;
               INTEGER32      max;
               DOMAIN         plot;
               UNSIGNED32     triggerTime;
               }              OD_trace_t;

/*******************************************************************************
   TYPE DEFINITIONS FOR OBJECT DICTIONARY INDEXES

   some of those are redundant with CO_SDO.h CO_ObjDicId_t <Common CiA301 object
   dictionary entries>
*******************************************************************************/
/*1000 */
        #define OD_1000_deviceType                                  0x1000

/*1001 */
        #define OD_1001_errorRegister                               0x1001

/*1002 */
        #define OD_1002_manufacturerStatusRegister                  0x1002

/*1003 */
        #define OD_1003_preDefinedErrorField                        0x1003

        #define OD_1003_0_preDefinedErrorField_maxSubIndex          0
        #define OD_1003_1_preDefinedErrorField_standardErrorField   1
        #define OD_1003_2_preDefinedErrorField_standardErrorField   2
        #define OD_1003_3_preDefinedErrorField_standardErrorField   3
        #define OD_1003_4_preDefinedErrorField_standardErrorField   4
        #define OD_1003_5_preDefinedErrorField_standardErrorField   5
        #define OD_1003_6_preDefinedErrorField_standardErrorField   6
        #define OD_1003_7_preDefinedErrorField_standardErrorField   7
        #define OD_1003_8_preDefinedErrorField_standardErrorField   8

/*1005 */
        #define OD_1005_COB_ID_SYNCMessage                          0x1005

/*1006 */
        #define OD_1006_communicationCyclePeriod                    0x1006

/*1007 */
        #define OD_1007_synchronousWindowLength                     0x1007

/*1008 */
        #define OD_1008_manufacturerDeviceName                      0x1008

/*1009 */
        #define OD_1009_manufacturerHardwareVersion                 0x1009

/*100A */
        #define OD_100A_manufacturerSoftwareVersion                 0x100A

/*1010 */
        #define OD_1010_storeParameters                             0x1010

        #define OD_1010_0_storeParameters_maxSubIndex               0
        #define OD_1010_1_storeParameters_saveAllParameters         1

/*1011 */
        #define OD_1011_restoreDefaultParameters                    0x1011

        #define OD_1011_0_restoreDefaultParameters_maxSubIndex      0
        #define OD_1011_1_restoreDefaultParameters_restoreAllDefaultParameters 1

/*1014 */
        #define OD_1014_COB_ID_EMCY                                 0x1014

/*1015 */
        #define OD_1015_inhibitTimeEMCY                             0x1015

/*1016 */
        #define OD_1016_consumerHeartbeatTime                       0x1016

        #define OD_1016_0_consumerHeartbeatTime_maxSubIndex         0
        #define OD_1016_1_consumerHeartbeatTime_consumerHeartbeatTime 1
        #define OD_1016_2_consumerHeartbeatTime_consumerHeartbeatTime 2
        #define OD_1016_3_consumerHeartbeatTime_consumerHeartbeatTime 3
        #define OD_1016_4_consumerHeartbeatTime_consumerHeartbeatTime 4

/*1017 */
        #define OD_1017_producerHeartbeatTime                       0x1017

/*1018 */
        #define OD_1018_identity                                    0x1018

        #define OD_1018_0_identity_maxSubIndex                      0
        #define OD_1018_1_identity_vendorID                         1
        #define OD_1018_2_identity_productCode                      2
        #define OD_1018_3_identity_revisionNumber                   3
        #define OD_1018_4_identity_serialNumber                     4

/*1019 */
        #define OD_1019_synchronousCounterOverflowValue             0x1019

/*1029 */
        #define OD_1029_errorBehavior                               0x1029

        #define OD_1029_0_errorBehavior_maxSubIndex                 0
        #define OD_1029_1_errorBehavior_communication               1
        #define OD_1029_2_errorBehavior_communicationOther          2
        #define OD_1029_3_errorBehavior_communicationPassive        3
        #define OD_1029_4_errorBehavior_generic                     4
        #define OD_1029_5_errorBehavior_deviceProfile               5
        #define OD_1029_6_errorBehavior_manufacturerSpecific        6

/*1200 */
        #define OD_1200_SDOServerParameter                          0x1200

        #define OD_1200_0_SDOServerParameter_maxSubIndex            0
        #define OD_1200_1_SDOServerParameter_COB_IDClientToServer   1
        #define OD_1200_2_SDOServerParameter_COB_IDServerToClient   2

/*1402 */
        #define OD_1402_RPDOCommunicationParameter                  0x1402

        #define OD_1402_0_RPDOCommunicationParameter_maxSubIndex    0
        #define OD_1402_1_RPDOCommunicationParameter_COB_IDUsedByRPDO 1
        #define OD_1402_2_RPDOCommunicationParameter_transmissionType 2

/*1602 */
        #define OD_1602_RPDOMappingParameter                        0x1602

        #define OD_1602_0_RPDOMappingParameter_maxSubIndex          0
        #define OD_1602_1_RPDOMappingParameter_applicationObject1   1
        #define OD_1602_2_RPDOMappingParameter_applicationObject2   2
        #define OD_1602_3_RPDOMappingParameter_applicationObject3   3
        #define OD_1602_4_RPDOMappingParameter_applicationObject4   4
        #define OD_1602_5_RPDOMappingParameter_applicationObject5   5
        #define OD_1602_6_RPDOMappingParameter_applicationObject6   6
        #define OD_1602_7_RPDOMappingParameter_applicationObject7   7
        #define OD_1602_8_RPDOMappingParameter_applicationObject8   8

/*1800 */
        #define OD_1800_TPDOCommunicationParameter                  0x1800

        #define OD_1800_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1800_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1800_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1800_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1800_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1800_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1800_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1801 */
        #define OD_1801_TPDOCommunicationParameter                  0x1801

        #define OD_1801_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1801_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1801_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1801_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1801_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1801_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1801_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1802 */
        #define OD_1802_TPDOCommunicationParameter                  0x1802

        #define OD_1802_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1802_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1802_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1802_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1802_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1802_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1802_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1803 */
        #define OD_1803_TPDOCommunicationParameter                  0x1803

        #define OD_1803_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1803_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1803_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1803_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1803_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1803_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1803_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1A00 */
        #define OD_1A00_TPDOMappingParameter                        0x1A00

        #define OD_1A00_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A00_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A00_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A00_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A00_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A00_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A00_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A00_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A00_8_TPDOMappingParameter_applicationObject8   8

/*1A01 */
        #define OD_1A01_TPDOMappingParameter                        0x1A01

        #define OD_1A01_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A01_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A01_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A01_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A01_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A01_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A01_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A01_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A01_8_TPDOMappingParameter_applicationObject8   8

/*1A02 */
        #define OD_1A02_TPDOMappingParameter                        0x1A02

        #define OD_1A02_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A02_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A02_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A02_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A02_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A02_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A02_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A02_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A02_8_TPDOMappingParameter_applicationObject8   8

/*1A03 */
        #define OD_1A03_TPDOMappingParameter                        0x1A03

        #define OD_1A03_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A03_1_TPDOMappingParameter_applicationObject1   1
        #define OD_1A03_2_TPDOMappingParameter_applicationObject2   2
        #define OD_1A03_3_TPDOMappingParameter_applicationObject3   3
        #define OD_1A03_4_TPDOMappingParameter_applicationObject4   4
        #define OD_1A03_5_TPDOMappingParameter_applicationObject5   5
        #define OD_1A03_6_TPDOMappingParameter_applicationObject6   6
        #define OD_1A03_7_TPDOMappingParameter_applicationObject7   7
        #define OD_1A03_8_TPDOMappingParameter_applicationObject8   8

/*1F80 */
        #define OD_1F80_NMTStartup                                  0x1F80

/*2100 */
        #define OD_2100_errorStatusBits                             0x2100

/*2101 */
        #define OD_2101_CANNodeID                                   0x2101

/*2102 */
        #define OD_2102_CANBitRate                                  0x2102

/*2103 */
        #define OD_2103_SYNCCounter                                 0x2103

/*2104 */
        #define OD_2104_SYNCTime                                    0x2104

/*2106 */
        #define OD_2106_powerOnCounter                              0x2106

/*2107 */
        #define OD_2107_performance                                 0x2107

        #define OD_2107_0_performance_maxSubIndex                   0
        #define OD_2107_1_performance_cyclesPerSecond               1
        #define OD_2107_2_performance_timerCycleTime                2
        #define OD_2107_3_performance_timerCycleMaxTime             3
        #define OD_2107_4_performance_mainCycleTime                 4
        #define OD_2107_5_performance_mainCycleMaxTime              5

/*2108 */
        #define OD_2108_temperature                                 0x2108

        #define OD_2108_0_temperature_maxSubIndex                   0
        #define OD_2108_1_temperature_mainPCB                       1

/*2109 */
        #define OD_2109_voltage                                     0x2109

        #define OD_2109_0_voltage_maxSubIndex                       0
        #define OD_2109_1_voltage_mainPCBSupply                     1

/*2110 */
        #define OD_2110_variableInt32                               0x2110

        #define OD_2110_0_variableInt32_maxSubIndex                 0
        #define OD_2110_1_variableInt32_int32                       1
        #define OD_2110_2_variableInt32_int32                       2
        #define OD_2110_3_variableInt32_int32                       3
        #define OD_2110_4_variableInt32_int32                       4
        #define OD_2110_5_variableInt32_int32                       5
        #define OD_2110_6_variableInt32_int32                       6
        #define OD_2110_7_variableInt32_int32                       7
        #define OD_2110_8_variableInt32_int32                       8
        #define OD_2110_9_variableInt32_int32                       9
        #define OD_2110_10_variableInt32_int32                      10
        #define OD_2110_11_variableInt32_int32                      11
        #define OD_2110_12_variableInt32_int32                      12
        #define OD_2110_13_variableInt32_int32                      13
        #define OD_2110_14_variableInt32_int32                      14
        #define OD_2110_15_variableInt32_int32                      15
        #define OD_2110_16_variableInt32_int32                      16

/*2111 */
        #define OD_2111_variableROM_Int32                           0x2111

        #define OD_2111_0_variableROM_Int32_maxSubIndex             0
        #define OD_2111_1_variableROM_Int32_int32                   1
        #define OD_2111_2_variableROM_Int32_int32                   2
        #define OD_2111_3_variableROM_Int32_int32                   3
        #define OD_2111_4_variableROM_Int32_int32                   4
        #define OD_2111_5_variableROM_Int32_int32                   5
        #define OD_2111_6_variableROM_Int32_int32                   6
        #define OD_2111_7_variableROM_Int32_int32                   7
        #define OD_2111_8_variableROM_Int32_int32                   8
        #define OD_2111_9_variableROM_Int32_int32                   9
        #define OD_2111_10_variableROM_Int32_int32                  10
        #define OD_2111_11_variableROM_Int32_int32                  11
        #define OD_2111_12_variableROM_Int32_int32                  12
        #define OD_2111_13_variableROM_Int32_int32                  13
        #define OD_2111_14_variableROM_Int32_int32                  14
        #define OD_2111_15_variableROM_Int32_int32                  15
        #define OD_2111_16_variableROM_Int32_int32                  16

/*2112 */
        #define OD_2112_variableNV_Int32                            0x2112

        #define OD_2112_0_variableNV_Int32_maxSubIndex              0
        #define OD_2112_1_variableNV_Int32_int32                    1
        #define OD_2112_2_variableNV_Int32_int32                    2
        #define OD_2112_3_variableNV_Int32_int32                    3
        #define OD_2112_4_variableNV_Int32_int32                    4
        #define OD_2112_5_variableNV_Int32_int32                    5
        #define OD_2112_6_variableNV_Int32_int32                    6
        #define OD_2112_7_variableNV_Int32_int32                    7
        #define OD_2112_8_variableNV_Int32_int32                    8
        #define OD_2112_9_variableNV_Int32_int32                    9
        #define OD_2112_10_variableNV_Int32_int32                   10
        #define OD_2112_11_variableNV_Int32_int32                   11
        #define OD_2112_12_variableNV_Int32_int32                   12
        #define OD_2112_13_variableNV_Int32_int32                   13
        #define OD_2112_14_variableNV_Int32_int32                   14
        #define OD_2112_15_variableNV_Int32_int32                   15
        #define OD_2112_16_variableNV_Int32_int32                   16

/*2120 */
        #define OD_2120_testVar                                     0x2120

        #define OD_2120_0_testVar_maxSubIndex                       0
        #define OD_2120_1_testVar_I64                               1
        #define OD_2120_2_testVar_U64                               2
        #define OD_2120_3_testVar_R32                               3
        #define OD_2120_4_testVar_R64                               4
        #define OD_2120_5_testVar_domain                            5

/*2130 */
        #define OD_2130_time                                        0x2130

        #define OD_2130_0_time_maxSubIndex                          0
        #define OD_2130_1_time_string                               1
        #define OD_2130_2_time_epochTimeBaseMs                      2
        #define OD_2130_3_time_epochTimeOffsetMs                    3

/*2301 */
        #define OD_2301_traceConfig                                 0x2301

        #define OD_2301_0_traceConfig_maxSubIndex                   0
        #define OD_2301_1_traceConfig_size                          1
        #define OD_2301_2_traceConfig_axisNo                        2
        #define OD_2301_3_traceConfig_name                          3
        #define OD_2301_4_traceConfig_color                         4
        #define OD_2301_5_traceConfig_map                           5
        #define OD_2301_6_traceConfig_format                        6
        #define OD_2301_7_traceConfig_trigger                       7
        #define OD_2301_8_traceConfig_threshold                     8

/*2302 */
        #define OD_2302_traceConfig                                 0x2302

        #define OD_2302_0_traceConfig_maxSubIndex                   0
        #define OD_2302_1_traceConfig_size                          1
        #define OD_2302_2_traceConfig_axisNo                        2
        #define OD_2302_3_traceConfig_name                          3
        #define OD_2302_4_traceConfig_color                         4
        #define OD_2302_5_traceConfig_map                           5
        #define OD_2302_6_traceConfig_format                        6
        #define OD_2302_7_traceConfig_trigger                       7
        #define OD_2302_8_traceConfig_threshold                     8

/*2400 */
        #define OD_2400_traceEnable                                 0x2400

/*2401 */
        #define OD_2401_trace                                       0x2401

        #define OD_2401_0_trace_maxSubIndex                         0
        #define OD_2401_1_trace_size                                1
        #define OD_2401_2_trace_value                               2
        #define OD_2401_3_trace_min                                 3
        #define OD_2401_4_trace_max                                 4
        #define OD_2401_5_trace_plot                                5
        #define OD_2401_6_trace_triggerTime                         6

/*2402 */
        #define OD_2402_trace                                       0x2402

        #define OD_2402_0_trace_maxSubIndex                         0
        #define OD_2402_1_trace_size                                1
        #define OD_2402_2_trace_value                               2
        #define OD_2402_3_trace_min                                 3
        #define OD_2402_4_trace_max                                 4
        #define OD_2402_5_trace_plot                                5
        #define OD_2402_6_trace_triggerTime                         6

/*6501 */
        #define OD_6501_ERROR_Packet                                0x6501

        #define OD_6501_0_ERROR_Packet_maxSubIndex                  0
        #define OD_6501_1_ERROR_Packet_times                        1
        #define OD_6501_2_ERROR_Packet_SOX                          2
        #define OD_6501_3_ERROR_Packet_temperature                  3
        #define OD_6501_4_ERROR_Packet_humidity                     4
        #define OD_6501_5_ERROR_Packet_ERROR_TIME                   5

/*6506 */
        #define OD_6506_remoteGateDriverConfigLow                   0x6506

        #define OD_6506_0_remoteGateDriverConfigLow_maxSubIndex     0
        #define OD_6506_1_remoteGateDriverConfigLow_I2C_ADD         1
        #define OD_6506_2_remoteGateDriverConfigLow_I2C_GADD        2
        #define OD_6506_3_remoteGateDriverConfigLow_I2CCFGOK        3
        #define OD_6506_4_remoteGateDriverConfigLow_IN_SUPR         4
        #define OD_6506_5_remoteGateDriverConfigLow_FSCLR_CFG       5
        #define OD_6506_6_remoteGateDriverConfigLow_FSCLR_T         6
        #define OD_6506_7_remoteGateDriverConfigLow_RECOVER         7
        #define OD_6506_8_remoteGateDriverConfigLow_RESTORE         8
        #define OD_6506_9_remoteGateDriverConfigLow_UVVEE2TL        9
        #define OD_6506_10_remoteGateDriverConfigLow_UVVCC2TL       10
        #define OD_6506_11_remoteGateDriverConfigLow_UVSVCC2L       11
        #define OD_6506_12_remoteGateDriverConfigLow_UVSVCC2E       12
        #define OD_6506_13_remoteGateDriverConfigLow_UVSVEE2L       13
        #define OD_6506_14_remoteGateDriverConfigLow_UVSVEE2E       14
        #define OD_6506_15_remoteGateDriverConfigLow_VINT_EN        15
        #define OD_6506_16_remoteGateDriverConfigLow_VEXT_EN        16
        #define OD_6506_17_remoteGateDriverConfigLow_VEXTLPOL       17
        #define OD_6506_18_remoteGateDriverConfigLow_VEXTL_EN       18
        #define OD_6506_19_remoteGateDriverConfigLow_VEXT_LIM       19
        #define OD_6506_20_remoteGateDriverConfigLow_OTW_LVL        20
        #define OD_6506_21_remoteGateDriverConfigLow_OTW_ACFG       21
        #define OD_6506_22_remoteGateDriverConfigLow_D_DIS          22
        #define OD_6506_23_remoteGateDriverConfigLow_D1_V_LVL       23
        #define OD_6506_24_remoteGateDriverConfigLow_D1FILT_C       24
        #define OD_6506_25_remoteGateDriverConfigLow_D1FILT_T       25
        #define OD_6506_26_remoteGateDriverConfigLow_D2_V_LVL       26
        #define OD_6506_27_remoteGateDriverConfigLow_D2_ACFG        27
        #define OD_6506_28_remoteGateDriverConfigLow_D2_TLCFG       28
        #define OD_6506_29_remoteGateDriverConfigLow_D2FILT_C       29
        #define OD_6506_30_remoteGateDriverConfigLow_D2FILT_T       30
        #define OD_6506_31_remoteGateDriverConfigLow_D2CNTLIM       31
        #define OD_6506_32_remoteGateDriverConfigLow_D2CNTDEC       32
        #define OD_6506_33_remoteGateDriverConfigLow_D_LEB_T        33
        #define OD_6506_34_remoteGateDriverConfigLow_F2O_DLY        34
        #define OD_6506_35_remoteGateDriverConfigLow_DTE_OS         35
        #define OD_6506_36_remoteGateDriverConfigLow_DTE_COEF       36
        #define OD_6506_37_remoteGateDriverConfigLow_DRV_FOFF       37
        #define OD_6506_38_remoteGateDriverConfigLow_STD_OFF        38
        #define OD_6506_39_remoteGateDriverConfigLow_TLTO_GCH       39
        #define OD_6506_40_remoteGateDriverConfigLow_TLTO_RA        40
        #define OD_6506_41_remoteGateDriverConfigLow_TLTO_V         41
        #define OD_6506_42_remoteGateDriverConfigLow_TLTO_T         42
        #define OD_6506_43_remoteGateDriverConfigLow_TLTO_RB        43
        #define OD_6506_44_remoteGateDriverConfigLow_CSSOFF_I       44
        #define OD_6506_45_remoteGateDriverConfigLow_CL_DIS         45
        #define OD_6506_46_remoteGateDriverConfigLow_CL_TYPE        46
        #define OD_6506_47_remoteGateDriverConfigLow_CLFILT_C       47
        #define OD_6506_48_remoteGateDriverConfigLow_CLFILT_T       48
        #define OD_6506_49_remoteGateDriverConfigLow_SOTOUT_F       49
        #define OD_6506_50_remoteGateDriverConfigLow_SOTOUT_T       50
        #define OD_6506_51_remoteGateDriverConfigLow_USER_OK        51
        #define OD_6506_52_remoteGateDriverConfigLow_SOFT_RST       52
        #define OD_6506_53_remoteGateDriverConfigLow_EVTSI_CL       53
        #define OD_6506_54_remoteGateDriverConfigLow_UV1F_CL        54
        #define OD_6506_55_remoteGateDriverConfigLow_UV2F_CL        55
        #define OD_6506_56_remoteGateDriverConfigLow_D2E_CL         56
        #define OD_6506_57_remoteGateDriverConfigLow_CHIP_RDY       57
        #define OD_6506_58_remoteGateDriverConfigLow_PRI_RDY        58
        #define OD_6506_59_remoteGateDriverConfigLow_SEC_RDY        59
        #define OD_6506_60_remoteGateDriverConfigLow_UV_VCC2        60
        #define OD_6506_61_remoteGateDriverConfigLow_UV_VEE2        61
        #define OD_6506_62_remoteGateDriverConfigLow_UVSVCC2        62
        #define OD_6506_63_remoteGateDriverConfigLow_UVSVEE2        63
        #define OD_6506_64_remoteGateDriverConfigLow_INT_PWR        64
        #define OD_6506_65_remoteGateDriverConfigLow_PRI_FLTN       65
        #define OD_6506_66_remoteGateDriverConfigLow_SEC_FLTN       66
        #define OD_6506_67_remoteGateDriverConfigLow_D1_EVT         67
        #define OD_6506_68_remoteGateDriverConfigLow_D2_EVT         68
        #define OD_6506_69_remoteGateDriverConfigLow_OTP_EVT        69
        #define OD_6506_70_remoteGateDriverConfigLow_OTW_EVT        70
        #define OD_6506_71_remoteGateDriverConfigLow_SOTO_EVT       71
        #define OD_6506_72_remoteGateDriverConfigLow_VOUT_ST        72
        #define OD_6506_73_remoteGateDriverConfigLow_VEXTFLT        73
        #define OD_6506_74_remoteGateDriverConfigLow_TLTO_LVL       74
        #define OD_6506_75_remoteGateDriverConfigLow_OFF_PIN        75
        #define OD_6506_76_remoteGateDriverConfigLow_ON_PIN         76
        #define OD_6506_77_remoteGateDriverConfigLow_PWM_PIN        77
        #define OD_6506_78_remoteGateDriverConfigLow_RDYC           78
        #define OD_6506_79_remoteGateDriverConfigLow_FLT_N          79
        #define OD_6506_80_remoteGateDriverConfigLow_DCT_COM        80
        #define OD_6506_81_remoteGateDriverConfigLow_CRC_COM        81
        #define OD_6506_82_remoteGateDriverConfigLow_CRC_PRI        82
        #define OD_6506_83_remoteGateDriverConfigLow_CRC_SEC        83
        #define OD_6506_84_remoteGateDriverConfigLow_PCT_COM        84
        #define OD_6506_85_remoteGateDriverConfigLow_ACTIVE         85
        #define OD_6506_86_remoteGateDriverConfigLow_CONFIG         86
        #define OD_6506_87_remoteGateDriverConfigLow_SFAULT         87
        #define OD_6506_88_remoteGateDriverConfigLow_SNRDY          88
        #define OD_6506_89_remoteGateDriverConfigLow_SRECOVER       89
        #define OD_6506_90_remoteGateDriverConfigLow_SRESTORE       90
        #define OD_6506_91_remoteGateDriverConfigLow_SDCTCOM        91
        #define OD_6506_92_remoteGateDriverConfigLow_SCRCANY        92
        #define OD_6506_93_remoteGateDriverConfigLow_SPCTCOM        93
        #define OD_6506_94_remoteGateDriverConfigLow_UV1F_CNT       94
        #define OD_6506_95_remoteGateDriverConfigLow_UV2F_CNT       95
        #define OD_6506_96_remoteGateDriverConfigLow_D2_CNT         96
        #define OD_6506_97_remoteGateDriverConfigLow_VCC2GND2       97
        #define OD_6506_98_remoteGateDriverConfigLow_GND2VEE2       98
        #define OD_6506_99_remoteGateDriverConfigLow_VCC2VEE2       99
        #define OD_6506_100_remoteGateDriverConfigLow_TJ_OUT        100
        #define OD_6506_101_remoteGateDriverConfigLow_VEXTVEE2      101
        #define OD_6506_102_remoteGateDriverConfigLow_update_flag   102
        #define OD_6506_103_remoteGateDriverConfigLow_refresh_flag  103

/*6507 */
        #define OD_6507_remoteGateDriverConfigHigh                  0x6507

        #define OD_6507_0_remoteGateDriverConfigHigh_maxSubIndex    0
        #define OD_6507_1_remoteGateDriverConfigHigh_I2C_ADD        1
        #define OD_6507_2_remoteGateDriverConfigHigh_I2C_GADD       2
        #define OD_6507_3_remoteGateDriverConfigHigh_I2CCFGOK       3
        #define OD_6507_4_remoteGateDriverConfigHigh_IN_SUPR        4
        #define OD_6507_5_remoteGateDriverConfigHigh_FSCLR_CFG      5
        #define OD_6507_6_remoteGateDriverConfigHigh_FSCLR_T        6
        #define OD_6507_7_remoteGateDriverConfigHigh_RECOVER        7
        #define OD_6507_8_remoteGateDriverConfigHigh_RESTORE        8
        #define OD_6507_9_remoteGateDriverConfigHigh_UVVEE2TL       9
        #define OD_6507_10_remoteGateDriverConfigHigh_UVVCC2TL      10
        #define OD_6507_11_remoteGateDriverConfigHigh_UVSVCC2L      11
        #define OD_6507_12_remoteGateDriverConfigHigh_UVSVCC2E      12
        #define OD_6507_13_remoteGateDriverConfigHigh_UVSVEE2L      13
        #define OD_6507_14_remoteGateDriverConfigHigh_UVSVEE2E      14
        #define OD_6507_15_remoteGateDriverConfigHigh_VINT_EN       15
        #define OD_6507_16_remoteGateDriverConfigHigh_VEXT_EN       16
        #define OD_6507_17_remoteGateDriverConfigHigh_VEXTLPOL      17
        #define OD_6507_18_remoteGateDriverConfigHigh_VEXTL_EN      18
        #define OD_6507_19_remoteGateDriverConfigHigh_VEXT_LIM      19
        #define OD_6507_20_remoteGateDriverConfigHigh_OTW_LVL       20
        #define OD_6507_21_remoteGateDriverConfigHigh_OTW_ACFG      21
        #define OD_6507_22_remoteGateDriverConfigHigh_D_DIS         22
        #define OD_6507_23_remoteGateDriverConfigHigh_D1_V_LVL      23
        #define OD_6507_24_remoteGateDriverConfigHigh_D1FILT_C      24
        #define OD_6507_25_remoteGateDriverConfigHigh_D1FILT_T      25
        #define OD_6507_26_remoteGateDriverConfigHigh_D2_V_LVL      26
        #define OD_6507_27_remoteGateDriverConfigHigh_D2_ACFG       27
        #define OD_6507_28_remoteGateDriverConfigHigh_D2_TLCFG      28
        #define OD_6507_29_remoteGateDriverConfigHigh_D2FILT_C      29
        #define OD_6507_30_remoteGateDriverConfigHigh_D2FILT_T      30
        #define OD_6507_31_remoteGateDriverConfigHigh_D2CNTLIM      31
        #define OD_6507_32_remoteGateDriverConfigHigh_D2CNTDEC      32
        #define OD_6507_33_remoteGateDriverConfigHigh_D_LEB_T       33
        #define OD_6507_34_remoteGateDriverConfigHigh_F2O_DLY       34
        #define OD_6507_35_remoteGateDriverConfigHigh_DTE_OS        35
        #define OD_6507_36_remoteGateDriverConfigHigh_DTE_COEF      36
        #define OD_6507_37_remoteGateDriverConfigHigh_DRV_FOFF      37
        #define OD_6507_38_remoteGateDriverConfigHigh_STD_OFF       38
        #define OD_6507_39_remoteGateDriverConfigHigh_TLTO_GCH      39
        #define OD_6507_40_remoteGateDriverConfigHigh_TLTO_RA       40
        #define OD_6507_41_remoteGateDriverConfigHigh_TLTO_V        41
        #define OD_6507_42_remoteGateDriverConfigHigh_TLTO_T        42
        #define OD_6507_43_remoteGateDriverConfigHigh_TLTO_RB       43
        #define OD_6507_44_remoteGateDriverConfigHigh_CSSOFF_I      44
        #define OD_6507_45_remoteGateDriverConfigHigh_CL_DIS        45
        #define OD_6507_46_remoteGateDriverConfigHigh_CL_TYPE       46
        #define OD_6507_47_remoteGateDriverConfigHigh_CLFILT_C      47
        #define OD_6507_48_remoteGateDriverConfigHigh_CLFILT_T      48
        #define OD_6507_49_remoteGateDriverConfigHigh_SOTOUT_F      49
        #define OD_6507_50_remoteGateDriverConfigHigh_SOTOUT_T      50
        #define OD_6507_51_remoteGateDriverConfigHigh_USER_OK       51
        #define OD_6507_52_remoteGateDriverConfigHigh_SOFT_RST      52
        #define OD_6507_53_remoteGateDriverConfigHigh_EVTSI_CL      53
        #define OD_6507_54_remoteGateDriverConfigHigh_UV1F_CL       54
        #define OD_6507_55_remoteGateDriverConfigHigh_UV2F_CL       55
        #define OD_6507_56_remoteGateDriverConfigHigh_D2E_CL        56
        #define OD_6507_57_remoteGateDriverConfigHigh_CHIP_RDY      57
        #define OD_6507_58_remoteGateDriverConfigHigh_PRI_RDY       58
        #define OD_6507_59_remoteGateDriverConfigHigh_SEC_RDY       59
        #define OD_6507_60_remoteGateDriverConfigHigh_UV_VCC2       60
        #define OD_6507_61_remoteGateDriverConfigHigh_UV_VEE2       61
        #define OD_6507_62_remoteGateDriverConfigHigh_UVSVCC2       62
        #define OD_6507_63_remoteGateDriverConfigHigh_UVSVEE2       63
        #define OD_6507_64_remoteGateDriverConfigHigh_INT_PWR       64
        #define OD_6507_65_remoteGateDriverConfigHigh_PRI_FLTN      65
        #define OD_6507_66_remoteGateDriverConfigHigh_SEC_FLTN      66
        #define OD_6507_67_remoteGateDriverConfigHigh_D1_EVT        67
        #define OD_6507_68_remoteGateDriverConfigHigh_D2_EVT        68
        #define OD_6507_69_remoteGateDriverConfigHigh_OTP_EVT       69
        #define OD_6507_70_remoteGateDriverConfigHigh_OTW_EVT       70
        #define OD_6507_71_remoteGateDriverConfigHigh_SOTO_EVT      71
        #define OD_6507_72_remoteGateDriverConfigHigh_VOUT_ST       72
        #define OD_6507_73_remoteGateDriverConfigHigh_VEXTFLT       73
        #define OD_6507_74_remoteGateDriverConfigHigh_TLTO_LVL      74
        #define OD_6507_75_remoteGateDriverConfigHigh_OFF_PIN       75
        #define OD_6507_76_remoteGateDriverConfigHigh_ON_PIN        76
        #define OD_6507_77_remoteGateDriverConfigHigh_PWM_PIN       77
        #define OD_6507_78_remoteGateDriverConfigHigh_RDYC          78
        #define OD_6507_79_remoteGateDriverConfigHigh_FLT_N         79
        #define OD_6507_80_remoteGateDriverConfigHigh_DCT_COM       80
        #define OD_6507_81_remoteGateDriverConfigHigh_CRC_COM       81
        #define OD_6507_82_remoteGateDriverConfigHigh_CRC_PRI       82
        #define OD_6507_83_remoteGateDriverConfigHigh_CRC_SEC       83
        #define OD_6507_84_remoteGateDriverConfigHigh_PCT_COM       84
        #define OD_6507_85_remoteGateDriverConfigHigh_ACTIVE        85
        #define OD_6507_86_remoteGateDriverConfigHigh_CONFIG        86
        #define OD_6507_87_remoteGateDriverConfigHigh_SFAULT        87
        #define OD_6507_88_remoteGateDriverConfigHigh_SNRDY         88
        #define OD_6507_89_remoteGateDriverConfigHigh_SRECOVER      89
        #define OD_6507_90_remoteGateDriverConfigHigh_SRESTORE      90
        #define OD_6507_91_remoteGateDriverConfigHigh_SDCTCOM       91
        #define OD_6507_92_remoteGateDriverConfigHigh_SCRCANY       92
        #define OD_6507_93_remoteGateDriverConfigHigh_SPCTCOM       93
        #define OD_6507_94_remoteGateDriverConfigHigh_UV1F_CNT      94
        #define OD_6507_95_remoteGateDriverConfigHigh_UV2F_CNT      95
        #define OD_6507_96_remoteGateDriverConfigHigh_D2_CNT        96
        #define OD_6507_97_remoteGateDriverConfigHigh_VCC2GND2      97
        #define OD_6507_98_remoteGateDriverConfigHigh_GND2VEE2      98
        #define OD_6507_99_remoteGateDriverConfigHigh_VCC2VEE2      99
        #define OD_6507_100_remoteGateDriverConfigHigh_TJ_OUT       100
        #define OD_6507_101_remoteGateDriverConfigHigh_VEXTVEE2     101
        #define OD_6507_102_remoteGateDriverConfigHigh_update_flag  102
        #define OD_6507_103_remoteGateDriverConfigHigh_refresh_flag 103

/*6508 */
        #define OD_6508_control                                     0x6508

        #define OD_6508_0_control_maxSubIndex                       0
        #define OD_6508_1_control_CID                               1
        #define OD_6508_2_control_runLedTimes                       2
        #define OD_6508_3_control_runLedCnts                        3
        #define OD_6508_4_control_runVoltage                        4
        #define OD_6508_5_control_controlVoltage                    5
        #define OD_6508_6_control_gateDriverUpadte                  6
        #define OD_6508_7_control_currentTime                       7
        #define OD_6508_8_control_status                            8
        #define OD_6508_9_control_boardTempature                    9
        #define OD_6508_10_control_boardHumity                      10
        #define OD_6508_11_control_IGBT_Volage                      11
        #define OD_6508_12_control_IGBT_H_Tempature                 12
        #define OD_6508_13_control_IGBT_L_Tempature                 13
        #define OD_6508_14_control_gateDriverHStatus                14
        #define OD_6508_15_control_gateDriverLStatus                15
        #define OD_6508_16_control_gateDriverHerrCode               16
        #define OD_6508_17_control_gateDriverLerrCode               17

/*******************************************************************************
   STRUCTURES FOR VARIABLES IN DIFFERENT MEMORY LOCATIONS
*******************************************************************************/
#define  CO_OD_FIRST_LAST_WORD     0x55 //Any value from 0x01 to 0xFE. If changed, EEPROM will be reinitialized.

/***** Structure for RAM variables ********************************************/
struct sCO_OD_RAM{
               UNSIGNED32     FirstWord;

/*1000      */ UNSIGNED32     deviceType;
/*1001      */ UNSIGNED8      errorRegister;
/*1002      */ UNSIGNED32     manufacturerStatusRegister;
/*1003      */ UNSIGNED32      preDefinedErrorField[8];
/*1005      */ UNSIGNED32     COB_ID_SYNCMessage;
/*1006      */ UNSIGNED32     communicationCyclePeriod;
/*1007      */ UNSIGNED32     synchronousWindowLength;
/*1008      */ VISIBLE_STRING manufacturerDeviceName[11];
/*1009      */ VISIBLE_STRING manufacturerHardwareVersion[4];
/*100A      */ VISIBLE_STRING manufacturerSoftwareVersion[4];
/*1010      */ UNSIGNED32      storeParameters[1];
/*1011      */ UNSIGNED32      restoreDefaultParameters[1];
/*1014      */ UNSIGNED32     COB_ID_EMCY;
/*1015      */ UNSIGNED16     inhibitTimeEMCY;
/*1016      */ UNSIGNED32      consumerHeartbeatTime[4];
/*1017      */ UNSIGNED16     producerHeartbeatTime;
/*1018      */ OD_identity_t   identity;
/*1019      */ UNSIGNED8      synchronousCounterOverflowValue;
/*1029      */ UNSIGNED8       errorBehavior[6];
/*1200      */ OD_SDOServerParameter_t SDOServerParameter[1];
/*1800      */ OD_TPDOCommunicationParameter_t TPDOCommunicationParameter[4];
/*1A00      */ OD_TPDOMappingParameter_t TPDOMappingParameter[4];
/*1F80      */ UNSIGNED32     NMTStartup;
/*2100      */ OCTET_STRING   errorStatusBits[10];
/*2101      */ UNSIGNED8      CANNodeID;
/*2102      */ UNSIGNED16     CANBitRate;
/*2103      */ UNSIGNED16     SYNCCounter;
/*2104      */ UNSIGNED16     SYNCTime;
/*2106      */ UNSIGNED32     powerOnCounter;
/*2107      */ UNSIGNED16      performance[5];
/*2108      */ INTEGER16       temperature[1];
/*2109      */ INTEGER16       voltage[1];
/*2110      */ INTEGER32       variableInt32[16];
/*2111      */ INTEGER32       variableROM_Int32[16];
/*2112      */ INTEGER32       variableNV_Int32[16];
/*2120      */ OD_testVar_t    testVar;
/*2130      */ OD_time_t       time;
/*2301      */ OD_traceConfig_t traceConfig[2];
/*2400      */ UNSIGNED8      traceEnable;
/*2401      */ OD_trace_t      trace[2];
/*6501      */ UNSIGNED32      ERROR_Packet[5];
/*6506      */ UNSIGNED32      remoteGateDriverConfigLow[103];
/*6507      */ UNSIGNED32      remoteGateDriverConfigHigh[103];
/*6508      */ UNSIGNED32      control[17];

               UNSIGNED32     LastWord;
};

/***** Structure for ROM variables ********************************************/
struct sCO_OD_ROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for EEPROM variables ********************************************/
struct sCO_OD_EEPROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for PERSIST_COMM variables ********************************************/
struct sCO_OD_PERSIST_COMM{
               UNSIGNED32     FirstWord;

/*1402      */ OD_RPDOCommunicationParameter_t RPDOCommunicationParameter[1];
/*1602      */ OD_RPDOMappingParameter_t RPDOMappingParameter[1];

               UNSIGNED32     LastWord;
};

/***** Declaration of Object Dictionary variables *****************************/
extern struct sCO_OD_RAM CO_OD_RAM;

extern struct sCO_OD_ROM CO_OD_ROM;

extern struct sCO_OD_EEPROM CO_OD_EEPROM;

extern struct sCO_OD_PERSIST_COMM CO_OD_PERSIST_COMM;

/*******************************************************************************
   ALIASES FOR OBJECT DICTIONARY VARIABLES
*******************************************************************************/
/*1000, Data Type: UNSIGNED32 */
        #define OD_deviceType_idx                                   0x1000
        #define OD_deviceType                                       CO_OD_RAM.deviceType

/*1001, Data Type: UNSIGNED8 */
        #define OD_errorRegister_idx                                0x1001
        #define OD_errorRegister                                    CO_OD_RAM.errorRegister

/*1002, Data Type: UNSIGNED32 */
        #define OD_manufacturerStatusRegister_idx                   0x1002
        #define OD_manufacturerStatusRegister                       CO_OD_RAM.manufacturerStatusRegister

/*1003, Data Type: UNSIGNED32, Array[8] */
        #define OD_preDefinedErrorField_idx                         0x1003
        #define OD_preDefinedErrorField                             CO_OD_RAM.preDefinedErrorField
        #define ODL_preDefinedErrorField_arrayLength                8
        #define ODA_preDefinedErrorField_standardErrorField         0

/*1005, Data Type: UNSIGNED32 */
        #define OD_COB_ID_SYNCMessage_idx                           0x1005
        #define OD_COB_ID_SYNCMessage                               CO_OD_RAM.COB_ID_SYNCMessage

/*1006, Data Type: UNSIGNED32 */
        #define OD_communicationCyclePeriod_idx                     0x1006
        #define OD_communicationCyclePeriod                         CO_OD_RAM.communicationCyclePeriod

/*1007, Data Type: UNSIGNED32 */
        #define OD_synchronousWindowLength_idx                      0x1007
        #define OD_synchronousWindowLength                          CO_OD_RAM.synchronousWindowLength

/*1008, Data Type: VISIBLE_STRING */
        #define OD_manufacturerDeviceName_idx                       0x1008
        #define OD_manufacturerDeviceName                           CO_OD_RAM.manufacturerDeviceName
        #define ODL_manufacturerDeviceName_stringLength             11

/*1009, Data Type: VISIBLE_STRING */
        #define OD_manufacturerHardwareVersion_idx                  0x1009
        #define OD_manufacturerHardwareVersion                      CO_OD_RAM.manufacturerHardwareVersion
        #define ODL_manufacturerHardwareVersion_stringLength        4

/*100A, Data Type: VISIBLE_STRING */
        #define OD_manufacturerSoftwareVersion_idx                  0x100A
        #define OD_manufacturerSoftwareVersion                      CO_OD_RAM.manufacturerSoftwareVersion
        #define ODL_manufacturerSoftwareVersion_stringLength        4

/*1010, Data Type: UNSIGNED32, Array[1] */
        #define OD_storeParameters_idx                              0x1010
        #define OD_storeParameters                                  CO_OD_RAM.storeParameters
        #define ODL_storeParameters_arrayLength                     1
        #define ODA_storeParameters_saveAllParameters               0

/*1011, Data Type: UNSIGNED32, Array[1] */
        #define OD_restoreDefaultParameters_idx                     0x1011
        #define OD_restoreDefaultParameters                         CO_OD_RAM.restoreDefaultParameters
        #define ODL_restoreDefaultParameters_arrayLength            1
        #define ODA_restoreDefaultParameters_restoreAllDefaultParameters 0

/*1014, Data Type: UNSIGNED32 */
        #define OD_COB_ID_EMCY_idx                                  0x1014
        #define OD_COB_ID_EMCY                                      CO_OD_RAM.COB_ID_EMCY

/*1015, Data Type: UNSIGNED16 */
        #define OD_inhibitTimeEMCY_idx                              0x1015
        #define OD_inhibitTimeEMCY                                  CO_OD_RAM.inhibitTimeEMCY

/*1016, Data Type: UNSIGNED32, Array[4] */
        #define OD_consumerHeartbeatTime_idx                        0x1016
        #define OD_consumerHeartbeatTime                            CO_OD_RAM.consumerHeartbeatTime
        #define ODL_consumerHeartbeatTime_arrayLength               4
        #define ODA_consumerHeartbeatTime_consumerHeartbeatTime     0

/*1017, Data Type: UNSIGNED16 */
        #define OD_producerHeartbeatTime_idx                        0x1017
        #define OD_producerHeartbeatTime                            CO_OD_RAM.producerHeartbeatTime

/*1018, Data Type: identity_t */
        #define OD_identity_idx                                     0x1018
        #define OD_identity                                         CO_OD_RAM.identity

/*1019, Data Type: UNSIGNED8 */
        #define OD_synchronousCounterOverflowValue_idx              0x1019
        #define OD_synchronousCounterOverflowValue                  CO_OD_RAM.synchronousCounterOverflowValue

/*1029, Data Type: UNSIGNED8, Array[6] */
        #define OD_errorBehavior_idx                                0x1029
        #define OD_errorBehavior                                    CO_OD_RAM.errorBehavior
        #define ODL_errorBehavior_arrayLength                       6
        #define ODA_errorBehavior_communication                     0
        #define ODA_errorBehavior_communicationOther                1
        #define ODA_errorBehavior_communicationPassive              2
        #define ODA_errorBehavior_generic                           3
        #define ODA_errorBehavior_deviceProfile                     4
        #define ODA_errorBehavior_manufacturerSpecific              5

/*1200, Data Type: SDOServerParameter_t */
        #define OD_SDOServerParameter_idx                           0x1200
        #define OD_SDOServerParameter                               CO_OD_RAM.SDOServerParameter

/*1402, Data Type: RPDOCommunicationParameter_t */
        #define OD_RPDOCommunicationParameter_idx                   0x1402
        #define OD_RPDOCommunicationParameter                       CO_OD_PERSIST_COMM.RPDOCommunicationParameter

/*1602, Data Type: RPDOMappingParameter_t */
        #define OD_RPDOMappingParameter_idx                         0x1602
        #define OD_RPDOMappingParameter                             CO_OD_PERSIST_COMM.RPDOMappingParameter

/*1800, Data Type: TPDOCommunicationParameter_t */
        #define OD_TPDOCommunicationParameter_idx                   0x1800
        #define OD_TPDOCommunicationParameter                       CO_OD_RAM.TPDOCommunicationParameter

/*1A00, Data Type: TPDOMappingParameter_t */
        #define OD_TPDOMappingParameter_idx                         0x1A00
        #define OD_TPDOMappingParameter                             CO_OD_RAM.TPDOMappingParameter

/*1F80, Data Type: UNSIGNED32 */
        #define OD_NMTStartup_idx                                   0x1F80
        #define OD_NMTStartup                                       CO_OD_RAM.NMTStartup

/*2100, Data Type: OCTET_STRING */
        #define OD_errorStatusBits_idx                              0x2100
        #define OD_errorStatusBits                                  CO_OD_RAM.errorStatusBits
        #define ODL_errorStatusBits_stringLength                    10

/*2101, Data Type: UNSIGNED8 */
        #define OD_CANNodeID_idx                                    0x2101
        #define OD_CANNodeID                                        CO_OD_RAM.CANNodeID

/*2102, Data Type: UNSIGNED16 */
        #define OD_CANBitRate_idx                                   0x2102
        #define OD_CANBitRate                                       CO_OD_RAM.CANBitRate

/*2103, Data Type: UNSIGNED16 */
        #define OD_SYNCCounter_idx                                  0x2103
        #define OD_SYNCCounter                                      CO_OD_RAM.SYNCCounter

/*2104, Data Type: UNSIGNED16 */
        #define OD_SYNCTime_idx                                     0x2104
        #define OD_SYNCTime                                         CO_OD_RAM.SYNCTime

/*2106, Data Type: UNSIGNED32 */
        #define OD_powerOnCounter_idx                               0x2106
        #define OD_powerOnCounter                                   CO_OD_RAM.powerOnCounter

/*2107, Data Type: UNSIGNED16, Array[5] */
        #define OD_performance_idx                                  0x2107
        #define OD_performance                                      CO_OD_RAM.performance
        #define ODL_performance_arrayLength                         5
        #define ODA_performance_cyclesPerSecond                     0
        #define ODA_performance_timerCycleTime                      1
        #define ODA_performance_timerCycleMaxTime                   2
        #define ODA_performance_mainCycleTime                       3
        #define ODA_performance_mainCycleMaxTime                    4

/*2108, Data Type: INTEGER16, Array[1] */
        #define OD_temperature_idx                                  0x2108
        #define OD_temperature                                      CO_OD_RAM.temperature
        #define ODL_temperature_arrayLength                         1
        #define ODA_temperature_mainPCB                             0

/*2109, Data Type: INTEGER16, Array[1] */
        #define OD_voltage_idx                                      0x2109
        #define OD_voltage                                          CO_OD_RAM.voltage
        #define ODL_voltage_arrayLength                             1
        #define ODA_voltage_mainPCBSupply                           0

/*2110, Data Type: INTEGER32, Array[16] */
        #define OD_variableInt32_idx                                0x2110
        #define OD_variableInt32                                    CO_OD_RAM.variableInt32
        #define ODL_variableInt32_arrayLength                       16
        #define ODA_variableInt32_int32                             0

/*2111, Data Type: INTEGER32, Array[16] */
        #define OD_variableROM_Int32_idx                            0x2111
        #define OD_variableROM_Int32                                CO_OD_RAM.variableROM_Int32
        #define ODL_variableROM_Int32_arrayLength                   16
        #define ODA_variableROM_Int32_int32                         0

/*2112, Data Type: INTEGER32, Array[16] */
        #define OD_variableNV_Int32_idx                             0x2112
        #define OD_variableNV_Int32                                 CO_OD_RAM.variableNV_Int32
        #define ODL_variableNV_Int32_arrayLength                    16
        #define ODA_variableNV_Int32_int32                          0

/*2120, Data Type: testVar_t */
        #define OD_testVar_idx                                      0x2120
        #define OD_testVar                                          CO_OD_RAM.testVar

/*2130, Data Type: time_t */
        #define OD_time_idx                                         0x2130
        #define OD_time                                             CO_OD_RAM.time

/*2301, Data Type: traceConfig_t */
        #define OD_traceConfig_idx                                  0x2301
        #define OD_traceConfig                                      CO_OD_RAM.traceConfig

/*2400, Data Type: UNSIGNED8 */
        #define OD_traceEnable_idx                                  0x2400
        #define OD_traceEnable                                      CO_OD_RAM.traceEnable

/*2401, Data Type: trace_t */
        #define OD_trace_idx                                        0x2401
        #define OD_trace                                            CO_OD_RAM.trace

/*6501, Data Type: UNSIGNED32, Array[5] */
        #define OD_ERROR_Packet_idx                                 0x6501
        #define OD_ERROR_Packet                                     CO_OD_RAM.ERROR_Packet
        #define ODL_ERROR_Packet_arrayLength                        5
        #define ODA_ERROR_Packet_times                              0
        #define ODA_ERROR_Packet_SOX                                1
        #define ODA_ERROR_Packet_temperature                        2
        #define ODA_ERROR_Packet_humidity                           3
        #define ODA_ERROR_Packet_ERROR_TIME                         4

/*6506, Data Type: UNSIGNED32, Array[103] */
        #define OD_remoteGateDriverConfigLow_idx                    0x6506
        #define OD_remoteGateDriverConfigLow                        CO_OD_RAM.remoteGateDriverConfigLow
        #define ODL_remoteGateDriverConfigLow_arrayLength           103
        #define ODA_remoteGateDriverConfigLow_I2C_ADD               0
        #define ODA_remoteGateDriverConfigLow_I2C_GADD              1
        #define ODA_remoteGateDriverConfigLow_I2CCFGOK              2
        #define ODA_remoteGateDriverConfigLow_IN_SUPR               3
        #define ODA_remoteGateDriverConfigLow_FSCLR_CFG             4
        #define ODA_remoteGateDriverConfigLow_FSCLR_T               5
        #define ODA_remoteGateDriverConfigLow_RECOVER               6
        #define ODA_remoteGateDriverConfigLow_RESTORE               7
        #define ODA_remoteGateDriverConfigLow_UVVEE2TL              8
        #define ODA_remoteGateDriverConfigLow_UVVCC2TL              9
        #define ODA_remoteGateDriverConfigLow_UVSVCC2L              10
        #define ODA_remoteGateDriverConfigLow_UVSVCC2E              11
        #define ODA_remoteGateDriverConfigLow_UVSVEE2L              12
        #define ODA_remoteGateDriverConfigLow_UVSVEE2E              13
        #define ODA_remoteGateDriverConfigLow_VINT_EN               14
        #define ODA_remoteGateDriverConfigLow_VEXT_EN               15
        #define ODA_remoteGateDriverConfigLow_VEXTLPOL              16
        #define ODA_remoteGateDriverConfigLow_VEXTL_EN              17
        #define ODA_remoteGateDriverConfigLow_VEXT_LIM              18
        #define ODA_remoteGateDriverConfigLow_OTW_LVL               19
        #define ODA_remoteGateDriverConfigLow_OTW_ACFG              20
        #define ODA_remoteGateDriverConfigLow_D_DIS                 21
        #define ODA_remoteGateDriverConfigLow_D1_V_LVL              22
        #define ODA_remoteGateDriverConfigLow_D1FILT_C              23
        #define ODA_remoteGateDriverConfigLow_D1FILT_T              24
        #define ODA_remoteGateDriverConfigLow_D2_V_LVL              25
        #define ODA_remoteGateDriverConfigLow_D2_ACFG               26
        #define ODA_remoteGateDriverConfigLow_D2_TLCFG              27
        #define ODA_remoteGateDriverConfigLow_D2FILT_C              28
        #define ODA_remoteGateDriverConfigLow_D2FILT_T              29
        #define ODA_remoteGateDriverConfigLow_D2CNTLIM              30
        #define ODA_remoteGateDriverConfigLow_D2CNTDEC              31
        #define ODA_remoteGateDriverConfigLow_D_LEB_T               32
        #define ODA_remoteGateDriverConfigLow_F2O_DLY               33
        #define ODA_remoteGateDriverConfigLow_DTE_OS                34
        #define ODA_remoteGateDriverConfigLow_DTE_COEF              35
        #define ODA_remoteGateDriverConfigLow_DRV_FOFF              36
        #define ODA_remoteGateDriverConfigLow_STD_OFF               37
        #define ODA_remoteGateDriverConfigLow_TLTO_GCH              38
        #define ODA_remoteGateDriverConfigLow_TLTO_RA               39
        #define ODA_remoteGateDriverConfigLow_TLTO_V                40
        #define ODA_remoteGateDriverConfigLow_TLTO_T                41
        #define ODA_remoteGateDriverConfigLow_TLTO_RB               42
        #define ODA_remoteGateDriverConfigLow_CSSOFF_I              43
        #define ODA_remoteGateDriverConfigLow_CL_DIS                44
        #define ODA_remoteGateDriverConfigLow_CL_TYPE               45
        #define ODA_remoteGateDriverConfigLow_CLFILT_C              46
        #define ODA_remoteGateDriverConfigLow_CLFILT_T              47
        #define ODA_remoteGateDriverConfigLow_SOTOUT_F              48
        #define ODA_remoteGateDriverConfigLow_SOTOUT_T              49
        #define ODA_remoteGateDriverConfigLow_USER_OK               50
        #define ODA_remoteGateDriverConfigLow_SOFT_RST              51
        #define ODA_remoteGateDriverConfigLow_EVTSI_CL              52
        #define ODA_remoteGateDriverConfigLow_UV1F_CL               53
        #define ODA_remoteGateDriverConfigLow_UV2F_CL               54
        #define ODA_remoteGateDriverConfigLow_D2E_CL                55
        #define ODA_remoteGateDriverConfigLow_CHIP_RDY              56
        #define ODA_remoteGateDriverConfigLow_PRI_RDY               57
        #define ODA_remoteGateDriverConfigLow_SEC_RDY               58
        #define ODA_remoteGateDriverConfigLow_UV_VCC2               59
        #define ODA_remoteGateDriverConfigLow_UV_VEE2               60
        #define ODA_remoteGateDriverConfigLow_UVSVCC2               61
        #define ODA_remoteGateDriverConfigLow_UVSVEE2               62
        #define ODA_remoteGateDriverConfigLow_INT_PWR               63
        #define ODA_remoteGateDriverConfigLow_PRI_FLTN              64
        #define ODA_remoteGateDriverConfigLow_SEC_FLTN              65
        #define ODA_remoteGateDriverConfigLow_D1_EVT                66
        #define ODA_remoteGateDriverConfigLow_D2_EVT                67
        #define ODA_remoteGateDriverConfigLow_OTP_EVT               68
        #define ODA_remoteGateDriverConfigLow_OTW_EVT               69
        #define ODA_remoteGateDriverConfigLow_SOTO_EVT              70
        #define ODA_remoteGateDriverConfigLow_VOUT_ST               71
        #define ODA_remoteGateDriverConfigLow_VEXTFLT               72
        #define ODA_remoteGateDriverConfigLow_TLTO_LVL              73
        #define ODA_remoteGateDriverConfigLow_OFF_PIN               74
        #define ODA_remoteGateDriverConfigLow_ON_PIN                75
        #define ODA_remoteGateDriverConfigLow_PWM_PIN               76
        #define ODA_remoteGateDriverConfigLow_RDYC                  77
        #define ODA_remoteGateDriverConfigLow_FLT_N                 78
        #define ODA_remoteGateDriverConfigLow_DCT_COM               79
        #define ODA_remoteGateDriverConfigLow_CRC_COM               80
        #define ODA_remoteGateDriverConfigLow_CRC_PRI               81
        #define ODA_remoteGateDriverConfigLow_CRC_SEC               82
        #define ODA_remoteGateDriverConfigLow_PCT_COM               83
        #define ODA_remoteGateDriverConfigLow_ACTIVE                84
        #define ODA_remoteGateDriverConfigLow_CONFIG                85
        #define ODA_remoteGateDriverConfigLow_SFAULT                86
        #define ODA_remoteGateDriverConfigLow_SNRDY                 87
        #define ODA_remoteGateDriverConfigLow_SRECOVER              88
        #define ODA_remoteGateDriverConfigLow_SRESTORE              89
        #define ODA_remoteGateDriverConfigLow_SDCTCOM               90
        #define ODA_remoteGateDriverConfigLow_SCRCANY               91
        #define ODA_remoteGateDriverConfigLow_SPCTCOM               92
        #define ODA_remoteGateDriverConfigLow_UV1F_CNT              93
        #define ODA_remoteGateDriverConfigLow_UV2F_CNT              94
        #define ODA_remoteGateDriverConfigLow_D2_CNT                95
        #define ODA_remoteGateDriverConfigLow_VCC2GND2              96
        #define ODA_remoteGateDriverConfigLow_GND2VEE2              97
        #define ODA_remoteGateDriverConfigLow_VCC2VEE2              98
        #define ODA_remoteGateDriverConfigLow_TJ_OUT                99
        #define ODA_remoteGateDriverConfigLow_VEXTVEE2              100
        #define ODA_remoteGateDriverConfigLow_update_flag           101
        #define ODA_remoteGateDriverConfigLow_refresh_flag          102

/*6507, Data Type: UNSIGNED32, Array[103] */
        #define OD_remoteGateDriverConfigHigh_idx                   0x6507
        #define OD_remoteGateDriverConfigHigh                       CO_OD_RAM.remoteGateDriverConfigHigh
        #define ODL_remoteGateDriverConfigHigh_arrayLength          103
        #define ODA_remoteGateDriverConfigHigh_I2C_ADD              0
        #define ODA_remoteGateDriverConfigHigh_I2C_GADD             1
        #define ODA_remoteGateDriverConfigHigh_I2CCFGOK             2
        #define ODA_remoteGateDriverConfigHigh_IN_SUPR              3
        #define ODA_remoteGateDriverConfigHigh_FSCLR_CFG            4
        #define ODA_remoteGateDriverConfigHigh_FSCLR_T              5
        #define ODA_remoteGateDriverConfigHigh_RECOVER              6
        #define ODA_remoteGateDriverConfigHigh_RESTORE              7
        #define ODA_remoteGateDriverConfigHigh_UVVEE2TL             8
        #define ODA_remoteGateDriverConfigHigh_UVVCC2TL             9
        #define ODA_remoteGateDriverConfigHigh_UVSVCC2L             10
        #define ODA_remoteGateDriverConfigHigh_UVSVCC2E             11
        #define ODA_remoteGateDriverConfigHigh_UVSVEE2L             12
        #define ODA_remoteGateDriverConfigHigh_UVSVEE2E             13
        #define ODA_remoteGateDriverConfigHigh_VINT_EN              14
        #define ODA_remoteGateDriverConfigHigh_VEXT_EN              15
        #define ODA_remoteGateDriverConfigHigh_VEXTLPOL             16
        #define ODA_remoteGateDriverConfigHigh_VEXTL_EN             17
        #define ODA_remoteGateDriverConfigHigh_VEXT_LIM             18
        #define ODA_remoteGateDriverConfigHigh_OTW_LVL              19
        #define ODA_remoteGateDriverConfigHigh_OTW_ACFG             20
        #define ODA_remoteGateDriverConfigHigh_D_DIS                21
        #define ODA_remoteGateDriverConfigHigh_D1_V_LVL             22
        #define ODA_remoteGateDriverConfigHigh_D1FILT_C             23
        #define ODA_remoteGateDriverConfigHigh_D1FILT_T             24
        #define ODA_remoteGateDriverConfigHigh_D2_V_LVL             25
        #define ODA_remoteGateDriverConfigHigh_D2_ACFG              26
        #define ODA_remoteGateDriverConfigHigh_D2_TLCFG             27
        #define ODA_remoteGateDriverConfigHigh_D2FILT_C             28
        #define ODA_remoteGateDriverConfigHigh_D2FILT_T             29
        #define ODA_remoteGateDriverConfigHigh_D2CNTLIM             30
        #define ODA_remoteGateDriverConfigHigh_D2CNTDEC             31
        #define ODA_remoteGateDriverConfigHigh_D_LEB_T              32
        #define ODA_remoteGateDriverConfigHigh_F2O_DLY              33
        #define ODA_remoteGateDriverConfigHigh_DTE_OS               34
        #define ODA_remoteGateDriverConfigHigh_DTE_COEF             35
        #define ODA_remoteGateDriverConfigHigh_DRV_FOFF             36
        #define ODA_remoteGateDriverConfigHigh_STD_OFF              37
        #define ODA_remoteGateDriverConfigHigh_TLTO_GCH             38
        #define ODA_remoteGateDriverConfigHigh_TLTO_RA              39
        #define ODA_remoteGateDriverConfigHigh_TLTO_V               40
        #define ODA_remoteGateDriverConfigHigh_TLTO_T               41
        #define ODA_remoteGateDriverConfigHigh_TLTO_RB              42
        #define ODA_remoteGateDriverConfigHigh_CSSOFF_I             43
        #define ODA_remoteGateDriverConfigHigh_CL_DIS               44
        #define ODA_remoteGateDriverConfigHigh_CL_TYPE              45
        #define ODA_remoteGateDriverConfigHigh_CLFILT_C             46
        #define ODA_remoteGateDriverConfigHigh_CLFILT_T             47
        #define ODA_remoteGateDriverConfigHigh_SOTOUT_F             48
        #define ODA_remoteGateDriverConfigHigh_SOTOUT_T             49
        #define ODA_remoteGateDriverConfigHigh_USER_OK              50
        #define ODA_remoteGateDriverConfigHigh_SOFT_RST             51
        #define ODA_remoteGateDriverConfigHigh_EVTSI_CL             52
        #define ODA_remoteGateDriverConfigHigh_UV1F_CL              53
        #define ODA_remoteGateDriverConfigHigh_UV2F_CL              54
        #define ODA_remoteGateDriverConfigHigh_D2E_CL               55
        #define ODA_remoteGateDriverConfigHigh_CHIP_RDY             56
        #define ODA_remoteGateDriverConfigHigh_PRI_RDY              57
        #define ODA_remoteGateDriverConfigHigh_SEC_RDY              58
        #define ODA_remoteGateDriverConfigHigh_UV_VCC2              59
        #define ODA_remoteGateDriverConfigHigh_UV_VEE2              60
        #define ODA_remoteGateDriverConfigHigh_UVSVCC2              61
        #define ODA_remoteGateDriverConfigHigh_UVSVEE2              62
        #define ODA_remoteGateDriverConfigHigh_INT_PWR              63
        #define ODA_remoteGateDriverConfigHigh_PRI_FLTN             64
        #define ODA_remoteGateDriverConfigHigh_SEC_FLTN             65
        #define ODA_remoteGateDriverConfigHigh_D1_EVT               66
        #define ODA_remoteGateDriverConfigHigh_D2_EVT               67
        #define ODA_remoteGateDriverConfigHigh_OTP_EVT              68
        #define ODA_remoteGateDriverConfigHigh_OTW_EVT              69
        #define ODA_remoteGateDriverConfigHigh_SOTO_EVT             70
        #define ODA_remoteGateDriverConfigHigh_VOUT_ST              71
        #define ODA_remoteGateDriverConfigHigh_VEXTFLT              72
        #define ODA_remoteGateDriverConfigHigh_TLTO_LVL             73
        #define ODA_remoteGateDriverConfigHigh_OFF_PIN              74
        #define ODA_remoteGateDriverConfigHigh_ON_PIN               75
        #define ODA_remoteGateDriverConfigHigh_PWM_PIN              76
        #define ODA_remoteGateDriverConfigHigh_RDYC                 77
        #define ODA_remoteGateDriverConfigHigh_FLT_N                78
        #define ODA_remoteGateDriverConfigHigh_DCT_COM              79
        #define ODA_remoteGateDriverConfigHigh_CRC_COM              80
        #define ODA_remoteGateDriverConfigHigh_CRC_PRI              81
        #define ODA_remoteGateDriverConfigHigh_CRC_SEC              82
        #define ODA_remoteGateDriverConfigHigh_PCT_COM              83
        #define ODA_remoteGateDriverConfigHigh_ACTIVE               84
        #define ODA_remoteGateDriverConfigHigh_CONFIG               85
        #define ODA_remoteGateDriverConfigHigh_SFAULT               86
        #define ODA_remoteGateDriverConfigHigh_SNRDY                87
        #define ODA_remoteGateDriverConfigHigh_SRECOVER             88
        #define ODA_remoteGateDriverConfigHigh_SRESTORE             89
        #define ODA_remoteGateDriverConfigHigh_SDCTCOM              90
        #define ODA_remoteGateDriverConfigHigh_SCRCANY              91
        #define ODA_remoteGateDriverConfigHigh_SPCTCOM              92
        #define ODA_remoteGateDriverConfigHigh_UV1F_CNT             93
        #define ODA_remoteGateDriverConfigHigh_UV2F_CNT             94
        #define ODA_remoteGateDriverConfigHigh_D2_CNT               95
        #define ODA_remoteGateDriverConfigHigh_VCC2GND2             96
        #define ODA_remoteGateDriverConfigHigh_GND2VEE2             97
        #define ODA_remoteGateDriverConfigHigh_VCC2VEE2             98
        #define ODA_remoteGateDriverConfigHigh_TJ_OUT               99
        #define ODA_remoteGateDriverConfigHigh_VEXTVEE2             100
        #define ODA_remoteGateDriverConfigHigh_update_flag          101
        #define ODA_remoteGateDriverConfigHigh_refresh_flag         102

/*6508, Data Type: UNSIGNED32, Array[17] */
        #define OD_control_idx                                      0x6508
        #define OD_control                                          CO_OD_RAM.control
        #define ODL_control_arrayLength                             17
        #define ODA_control_CID                                     0
        #define ODA_control_runLedTimes                             1
        #define ODA_control_runLedCnts                              2
        #define ODA_control_runVoltage                              3
        #define ODA_control_controlVoltage                          4
        #define ODA_control_gateDriverUpadte                        5
        #define ODA_control_currentTime                             6
        #define ODA_control_status                                  7
        #define ODA_control_boardTempature                          8
        #define ODA_control_boardHumity                             9
        #define ODA_control_IGBT_Volage                             10
        #define ODA_control_IGBT_H_Tempature                        11
        #define ODA_control_IGBT_L_Tempature                        12
        #define ODA_control_gateDriverHStatus                       13
        #define ODA_control_gateDriverLStatus                       14
        #define ODA_control_gateDriverHerrCode                      15
        #define ODA_control_gateDriverLerrCode                      16

#endif
// clang-format on
