################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
build-1711646385: ../Source\ Code/source/CodeBoard.syscfg
	@echo 'Building file: "$<"'
	@echo 'Invoking: SysConfig'
	"D:/Ti/sysconfig_1.27.0/sysconfig_cli.bat" -s "D:/Ti/c2000/C2000Ware_5_04_00_00/.metadata/sdk.json" -d "F2837xD" -p "F2837xD_337ZWT" -r "F2837xD_337ZWT" --script "D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/source/CodeBoard.syscfg" --context "CPU1" -o "syscfg" --compiler ccs
	@echo 'Finished building: "$<"'
	@echo ' '

syscfg/board.c: build-1711646385 ../Source\ Code/source/CodeBoard.syscfg
syscfg/board.h: build-1711646385
syscfg/board.cmd.genlibs: build-1711646385
syscfg/board.opt: build-1711646385
syscfg/board.json: build-1711646385
syscfg/pinmux.csv: build-1711646385
syscfg/c2000ware_libraries.cmd.genlibs: build-1711646385
syscfg/c2000ware_libraries.opt: build-1711646385
syscfg/c2000ware_libraries.c: build-1711646385
syscfg/c2000ware_libraries.h: build-1711646385
syscfg/clocktree.h: build-1711646385
syscfg/: build-1711646385

syscfg/%.obj: ./syscfg/%.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="syscfg/$(basename $(<F)).d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="syscfg" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/PeripheralsInit.obj: ../Source\ Code/source/PeripheralsInit.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/PeripheralsInit.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/debug.obj: ../Source\ Code/source/debug.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/debug.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/isr.obj: ../Source\ Code/source/isr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/isr.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/main.obj: ../Source\ Code/source/main.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/main.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/my_adcContorl.obj: ../Source\ Code/source/my_adcContorl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/my_adcContorl.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/my_dma.obj: ../Source\ Code/source/my_dma.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/my_dma.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/my_flash.obj: ../Source\ Code/source/my_flash.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/my_flash.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/my_fram.obj: ../Source\ Code/source/my_fram.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/my_fram.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/my_sci.obj: ../Source\ Code/source/my_sci.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/my_sci.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/my_spi.obj: ../Source\ Code/source/my_spi.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/my_spi.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Source\ Code/source/my_xmif.obj: ../Source\ Code/source/my_xmif.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/Ti/LT226/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O0 --opt_for_speed=1 --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/common/include/" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/device_support/f2837xd/headers/include/" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/device" --include_path="D:/Ti/c2000/C2000Ware_5_04_00_00/driverlib/f2837xd/driverlib/" --include_path="D:/Ti/LT226/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/include" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/W5500" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/PWM" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/modbus" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/DIDO" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/GlobalVarivables" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/APP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN/lib/CANopen/DSP" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/CAN" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/Source Code/Contorl" --advice:performance=all --define=DEBUG --define=_DUAL_HEADERS --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --abi=coffabi --preproc_with_compile --preproc_dependency="Source Code/source/my_xmif.d_raw" --include_path="D:/li/Simulation/HKRPTS_Simulation/CCS/CodeBoard/F28377_RAM/syscfg" --obj_directory="Source Code/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


